name: Python

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Use ruff-action so we get annotations in the GitHub UI.
      - uses: astral-sh/ruff-action@v3

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: uv sync
        run: uv sync --no-install-package zarrsita

      - name: maturin develop
        run: uv run --no-project maturin develop

      - name: Run pytest
        run: uv run --no-project pytest --verbose
